---
version: "3.9"
services:
  flm:
    container_name: aws
    image: httpd
    ports:
      - "8081:80"


  devops:
    container_name: devops
    image: nginx
    ports:
      - "8082:80"

    volumes:
      - "myvolume"
      
      - "newvolume"


networks:
  prasad:
    driver: bridge


    networks:
      - "prasad"

      ################
 upstream loadbalancer {
 server 172.17.0.1:5001 weight=6;
 server 172.17.0.1:5002 weight=4;
}

server {
    location / {
         proxy_pass httpd://loadbalancer;
    }
}
